ÃÂ•À€À€À€À€_À€À€À€À€À€À€À€À€À€À€À€À€À€À€À€À€À€À€À€À€À€À€	À€À€À€À€À€À€À€)À€À€À€3À€À€#À€À€À€]À€À€"À€À€À€ÂÀ€À€À€À€À€Â¤À€À€&À€À€À€Ã€À€À€À€À€À€Ã§À€À€À€À€À€Ã¹À€À€*À€À€À€	À€À€$À€À€À€9	À€À€!À€À€À€^	À€À€À€À€À€Â€	À€À€8À€À€À€Âœ	À€À€À€À€À€Ã•	À€À€À€À€À€Ã´	À€À€!À€À€À€
À€À€À€À€À€.
À€À€À€À€À€E
À€À€À€À€À€_
À€À€(À€À€À€z
À€À€$À€À€À€Â£
À€À€À€À€À€Ãˆ
À€À€À€À€À€Ã¥
À€À€À€À€À€À€À€'À€À€À€À€À€À€À€À€FÀ€À€À€À€À€cÀ€À€#À€À€À€~À€À€4À€À€À€Â¢À€À€À€À€À€Ã—À€À€À€À€À€Ã®À€À€À€À€À€
À€À€;À€À€À€&À€À€AÀ€À€À€bÀ€À€8À€À€À€Â¤À€À€FÀ€À€À€ÃÀ€À€=À€À€À€$
À€À€À€À€À€b
À€À€À€À€À€Â
À€À€À€À€À€ÂŸ
À€À€À€À€À€Â¸
À€À€À€À€À€Ã‡
À€À€"À€À€À€ÃŸ
À€À€VÀ€À€À€À€À€'À€À€À€YÀ€À€
À€À€À€ÂÀ€À€EÀ€À€À€ÂÀ€À€+À€À€À€Ã•À€À€8À€À€À€À€À€À€À€À€:À€À€-À€À€À€SÀ€À€(À€À€À€ÂÀ€À€1À€À€À€ÂªÀ€À€'À€À€À€ÃœÀ€À€À€À€À€À€À€"À€À€À€À€À€À€À€À€@À€À€#À€À€À€WÀ€À€,À€À€À€{À€À€À€À€À€Â¨À€À€
À€À€À€ÃÀ€À€&À€À€À€ÃÀ€À€À€À€À€Ã¶À€À€À€À€À€
À€À€3À€À€À€)À€À€(À€À€À€]À€À€CÀ€À€À€Â†À€À€%À€À€À€ÃŠÀ€À€+À€À€À€Ã°À€À€
À€À€À€À€À€#À€À€À€*À€À€À€À€À€NÀ€À€0À€À€À€mÀ€À€À€À€À€ÂÀ€À€À€À€À€Â­À€À€
À€À€À€Ã€À€À€À€À€À€ÃÀ€À€À€À€À€Ã¦À€À€+À€À€À€À€À€À€À€À€/À€À€*À€À€À€IÀ€À€À€À€À€tÀ€À€%À€À€À€Â‰À€À€*À€À€À€Â¯À€À€"À€À€À€ÃšÀ€À€À€À€À€Ã½À€À€À€À€À€À€À€%À€À€À€+À€À€ À€À€À€QÀ€À€À€À€À€rÀ€À€À€À€À€ÂÀ€À€2À€À€À€Â—À€À€%À€À€À€ÃŠÀ€À€UÀ€À€Ã°À€À€À€À€À€FÀ€À€À€À€À€[À€À€"À€À€À€lÀ€À€À€À€À€ÂÀ€À€À€À€À€Â¬À€À€À€À€À€Ã„À€À€À€À€À€Ã—À€À€À€À€À€Ã°À€À€À€À€À€Ã½À€À€"À€À€À€
À€À€À€À€À€-À€À€À€À€À€JÀ€À€À€À€À€iÀ€À€6À€À€À€Â‚À€À€À€À€À€Â¹À€À€À€À€À€Ã‘À€À€ À€À€À€Ã§À€À€À€À€À€À€À€À€À€À€À€À€À€À€À€1À€À€À€À€À€GÀ€À€À€À€À€aÀ€À€À€À€À€}À€À€À€À€À€Â•À€À€À€À€À€Â«À€À€À€À€À€Â¾À€À€À€À€À€Ã—À€À€À€À€À€Ã°À€À€%À€À€À€À€À€3À€À€À€)À€À€À€À€À€]À€À€À€À€À€pÀ€À€À€À€À€Â‰À€À€0À€À€À€Â¡À€À€3À€À€À€Ã’À€À€'À€À€À€À€À€KÀ€À€À€.À€À€0À€À€À€zÀ€À€À€À€À€Â«À€À€À€À€À€ÃÀ€À€À€À€À€Ã—À€À€À€À€À€Ã°À€À€À€À€À€À€À€"À€À€À€!À€À€WÀ€À€À€DÀ€À€&À€À€À€ÂœÀ€À€	À€À€À€ÃƒÀ€À€0À€À€À€ÃÀ€À€À€À€À€Ã¾À€À€.À€À€À€À€À€À€À€À€JÀ€À€À€À€À€`À€À€À€À€À€|À€À€*À€À€À€Â›À€À€$À€À€À€Ã†À€À€À€À€À€Ã«À€À€%À€À€À€Ã»À€À€À€À€À€!À€À€"À€À€À€9À€À€+À€À€À€\À€À€À€À€À€ÂˆÀ€À€À€À€À€Â£À€À€À€À€À€Â³À€À€À€À€À€Ã“À€À€À€À€À€Ã­À€À€0À€À€À€À€À€À€À€À€À€1À€À€8À€À€À€MÀ€À€À€À€À€Â†À€À€ À€À€À€Â¥À€À€À€À€À€Ã†À€À€À€À€À€Ã“À€À€À€À€À€Ã²À€À€0À€À€À€À€À€À€À€À€CÀ€À€À€À€À€RÀ€À€À€À€À€iÀ€À€À€À€À€{À€À€À€À€À€ÂÀ€À€*À€À€À€Â¡À€À€À€À€À€ÃŒÀ€À€$À€À€À€ÃŸÀ€À€À€À€À€ À€À€À€À€À€ À€À€$À€À€À€4 À€À€À€À€À€Y À€À€À€À€À€x À€À€À€À€À€Â‹ À€À€!À€À€À€Â§ À€À€!À€À€À€Ã‰ À€À€À€À€À€Ã« À€À€À€À€À€Ã¸ À€À€0À€À€À€!À€À€'À€À€À€@!À€À€À€À€À€À€À€À€À€	À€À€À€À€À€À€À€
À€À€À€7À€À€À€À€À€À€5À€À€À€À€À€À€À€À€À€À€À€À€À€À€À€À€À€À€À€À€À€À€À€À€À€>À€À€À€À€À€À€À€CÀ€À€À€YÀ€À€À€À€À€À€À€4À€À€À€À€À€À€À€À€À€À€GÀ€À€À€MÀ€À€À€"À€À€À€À€À€À€À€À€À€À€À€À€XÀ€À€À€ZÀ€À€À€WÀ€À€À€À€À€À€À€À€À€À€À€À€À€HÀ€À€À€9À€À€À€À€À€À€2À€À€À€3À€À€À€À€À€À€À€À€À€À€6À€À€À€$À€À€À€-À€À€À€À€À€À€À€À€À€À€À€À€À€OÀ€À€À€À€À€À€À€À€À€À€NÀ€À€À€^À€À€À€<À€À€À€RÀ€À€À€?À€À€À€ À€À€À€À€À€À€À€À€À€]À€À€À€LÀ€À€À€À€À€À€À€FÀ€À€À€+À€À€À€À€À€À€À€\À€À€À€À€À€À€À€'À€À€À€À€À€À€À€1À€À€À€À€À€À€À€;À€À€À€UÀ€À€À€PÀ€À€À€(À€À€À€À€À€À€À€IÀ€À€À€[À€À€À€À€À€À€.À€À€À€À€À€À€À€À€À€À€À€À€À€À€À€AÀ€À€À€À€À€À€À€À€À€)À€À€À€À€À€À€EÀ€À€À€BÀ€À€À€À€À€À€À€:À€À€À€À€À€À€À€À€À€À€À€À€À€*À€À€À€0À€À€À€%À€À€À€DÀ€À€À€
À€À€À€À€À€À€À€VÀ€À€À€À€À€À€8À€À€À€À€À€À€À€À€À€JÀ€À€À€À€À€À€KÀ€À€À€QÀ€À€À€À€À€À€À€À€À€À€À€#À€À€À€&À€À€À€À€À€À€À€TÀ€À€À€,À€À€À€=À€À€À€@À€À€À€À€À€À€À€!À€À€À€/À€À€À€_À€À€À€À€À€À€À€À€À€À€À€À€À€À€SÀ€À€À€À€À€À€À€À€%s: %s (code %d)À€%s: connection timed outÀ€%s: connection was closed by proxy serverÀ€%s: connection was closed by serverÀ€Certificate verification error: %sÀ€Chunk delimiter was invalidÀ€Client certificate verification failedÀ€Connection closedÀ€Connection timed outÀ€Could not authenticate to proxy server: %sÀ€Could not authenticate to server: %sÀ€Could not connect to proxy serverÀ€Could not connect to serverÀ€Could not create SSL connection through proxy server: %sÀ€Could not create SSL structureÀ€Could not create socketÀ€Could not determine file size: %sÀ€Could not inflate dataÀ€Could not initialize zlibÀ€Could not parse chunk sizeÀ€Could not parse redirect destination URLÀ€Could not parse response status lineÀ€Could not parse response: %sÀ€Could not read chunk delimiterÀ€Could not read chunk sizeÀ€Could not read interim response headersÀ€Could not read response bodyÀ€Could not read status lineÀ€Could not resolve hostname `%s': %sÀ€Could not seek to offset %s of request body file: %sÀ€Could not send requestÀ€Could not send request bodyÀ€Could not write to file: %sÀ€Digest mutual authentication failure: client nonce mismatchÀ€Digest mutual authentication failure: could not parse nonce countÀ€Digest mutual authentication failure: missing parametersÀ€Digest mutual authentication failure: nonce count mismatch (%u not %u)À€Digest mutual authentication failure: request-digest mismatchÀ€Error reading response headersÀ€GSSAPI authentication error: À€GSSAPI failure (code %u)À€Host not foundÀ€Invalid Byte Order MarkÀ€Invalid Content-Length in responseÀ€Invalid HTTP status line in status element at line %d of response:
Status line was: %sÀ€LOCK response missing Lock-Token headerÀ€Line too longÀ€Negotiate response verification failed: invalid response header tokenÀ€Negotiate response verification failure: %sÀ€No activelock for <%s> returned in LOCK refresh responseÀ€Range is not satisfiableÀ€Resource does not support ranged GET requestsÀ€Response did not include requested rangeÀ€Response exceeded maximum number of header fieldsÀ€Response exceeds maximum property countÀ€Response header too longÀ€Response missing activelock for %sÀ€SSL alert received: %sÀ€SSL disabled due to lack of entropyÀ€SSL disabled due to library version mismatchÀ€SSL error code %d/%d/%luÀ€SSL error: %sÀ€SSL server did not present certificateÀ€SSL socket read failedÀ€Secure connection truncatedÀ€Server certificate changed: connection intercepted?À€Server certificate verification failed: À€Server certificate was missing commonName attribute in subject nameÀ€Server did not send certificate chainÀ€Socket descriptor number exceeds FD_SETSIZEÀ€Unknown errorÀ€Unknown transfer-coding in responseÀ€XML parse error at line %d: %sÀ€XML parse error at line %d: invalid element nameÀ€[invalid date]À€[unprintable:#%lu]À€[unprintable]À€certificate has expiredÀ€certificate is not yet validÀ€certificate issued for a different hostnameÀ€could not parse challengeÀ€could not parse domain in Digest challengeÀ€ignored %s challengeÀ€ignoring empty Negotiate continuationÀ€incompatible algorithm in Digest challengeÀ€initial Digest challenge was staleÀ€invalid Negotiate tokenÀ€issuer is not trustedÀ€missing parameter in Digest challengeÀ€missing realm in Basic challengeÀ€offset invalidÀ€rejected %s challengeÀ€stale Digest challenge with new algorithm or realmÀ€unknown algorithm in Digest challengeÀ€Project-Id-Version: neon 0.29.x
Report-Msgid-Bugs-To: neon@lists.manyfish.co.uk
POT-Creation-Date: 2010-10-01 13:30+0100
PO-Revision-Date: 2008-03-03 11:20+0800
Last-Translator: Dongsheng Song <dongsheng.song@gmail.com>
Language-Team: neon@webdav.org
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
À€%sï¼š %s (ä»£ç  %d)À€%s: è¿æ¥è¶…æ—¶À€%s: è¿æ¥è¢«ä»£ç†æœåŠ¡å™¨å…³é—­À€%s: è¿æ¥è¢«æœåŠ¡å™¨å…³é—­À€è¯ä¹¦æ ¡éªŒå¤±è´¥ï¼š%sÀ€éæ³•çš„åˆ†å‰²ç¬¦À€å®¢æˆ·è¯ä¹¦æ ¡éªŒå¤±è´¥À€è¿æ¥å…³é—­À€è¿æ¥è¶…æ—¶À€ä¸èƒ½è®¤è¯åˆ°ä»£ç†æœåŠ¡å™¨: %sÀ€ä¸èƒ½è®¤è¯åˆ°æœåŠ¡å™¨: %sÀ€ä¸èƒ½è¿æ¥åˆ°ä»£ç†æœåŠ¡å™¨À€ä¸èƒ½è¿æ¥åˆ°æœåŠ¡å™¨À€ä¸èƒ½é€šè¿‡ä»£ç†æœåŠ¡å™¨ â€œ%sâ€ åˆ›å»º SSL è¿æ¥À€ä¸èƒ½åˆ›å»º SSL ç»“æ„À€ä¸èƒ½åˆ›å»ºå¥—æ¥å­—À€ä¸èƒ½ç¡®å®šçš„æ–‡ä»¶å¤§å°ï¼š%sÀ€è§£å‹æ•°æ®å¤±è´¥À€åˆå§‹åŒ– zlib å¤±è´¥À€ä¸èƒ½è§£æå—å¤§å°À€ä¸èƒ½è§£æé‡å®šå‘ URLÀ€ä¸èƒ½è§£æå“åº”çŠ¶æ€è¡ŒÀ€ä¸èƒ½è§£æå“åº”ï¼š%sÀ€ä¸èƒ½è¯»å—åˆ†å‰²ç¬¦À€ä¸èƒ½è¯»å—å¤§å°À€ä¸èƒ½è¯»ä¸´æ—¶å“åº”å¤´À€ä¸èƒ½è¯»å–å“åº”ä¸»ä½“À€ä¸èƒ½è¯»çŠ¶æ€è¡ŒÀ€ä¸èƒ½è§£æä¸»æœºåç§° â€œ%sâ€: %sÀ€åœ¨è¯·æ±‚ä¸»ä½“æ–‡ä»¶ä¸èƒ½å®šä½åˆ°åç§» %sï¼š %sÀ€ä¸èƒ½å‘é€è¯·æ±‚À€ä¸èƒ½å‘é€è¯·æ±‚ä¸»ä½“À€ä¸èƒ½å†™å…¥æ–‡ä»¶ï¼š%sÀ€æ‘˜è¦äº’ç›¸è®¤è¯å¤±è´¥ï¼šå®¢æˆ·ç°æ—¶ä¸åŒ¹é…À€æ‘˜è¦äº’ç›¸è®¤è¯å¤±è´¥ï¼šä¸èƒ½è§£æç°æ—¶è®¡æ•°À€æ‘˜è¦äº’ç›¸è®¤è¯å¤±è´¥ï¼šå‚æ•°é—æ¼À€æ‘˜è¦äº’ç›¸è®¤è¯å¤±è´¥ï¼šç°æ—¶è®¡ç®—ä¸åŒ¹é… (åº”è¯¥æ˜¯ %uï¼Œä¸æ˜¯ %u)À€æ‘˜è¦äº’ç›¸è®¤è¯å¤±è´¥ï¼šè¯·æ±‚æ‘˜è¦ä¸åŒ¹é…À€è¯»å–å“åº”å¤´å‡ºé”™À€GSSAPI è®¤è¯é”™è¯¯: À€GSSAPI å¤±è´¥(ä»£ç  %u)À€æ²¡æœ‰å‘ç°ä¸»æœºÀ€éæ³•å­—èŠ‚é¡ºåºæ ‡è®°(BOM)À€éæ³•çš„ Content-Length å“åº”åŸŸÀ€å“åº”ä¿¡æ¯ä¸­ %d è¡Œçš„çŠ¶æ€å…ƒç´ ä¸­å‘ç°éæ³• HTTP çŠ¶æ€è¡Œï¼š
çŠ¶æ€è¡Œæ˜¯: %sÀ€LOCK çš„å“åº”é—æ¼äº† Lock-Token è¡ŒÀ€è¡Œå¤ªé•¿À€æ ¡éªŒåå•†å“åº”å¤±è´¥ï¼šéæ³•å“åº”å¤´ä»¤ç‰ŒÀ€ç£‹å•†å“åº”æ ¡éªŒå¤±è´¥: %sÀ€åˆ·æ–°é”å®š %s çš„å“åº”æ²¡æœ‰è¿”å›ä¸»åŠ¨é”À€ä¸èƒ½æ»¡è¶³çš„èŒƒå›´À€èµ„æºä¸æ”¯æŒèŒƒå›´è¯»å–À€å“åº”æ²¡æœ‰åŒ…å«è¯·æ±‚èŒƒå›´À€å“åº”å¤´çš„åŸŸæ•°é‡è¶…å‡ºäº†æœ€å¤§æ•°é‡À€å“åº”è¶…è¿‡äº†å±æ€§çš„æœ€å¤§è®¡æ•°À€å“åº”å¤´å¤ªé•¿À€é”å®š %s çš„å“åº”é—æ¼äº†ä¸»åŠ¨é”À€æ”¶åˆ° SSL è­¦æŠ¥ï¼š %sÀ€ç”±äºç¼ºå°‘ç†µï¼ŒSSL å·²ç»ç¦ç”¨À€ç”±äºåº“ç‰ˆæœ¬ä¸åŒ¹é…ï¼ŒSSL å·²ç»ç¦ç”¨À€SSL é”™è¯¯ä»£ç  %d/%d/%luÀ€SSL é”™è¯¯ï¼š%sÀ€SSL æœåŠ¡å™¨ä¸èƒ½å‘ˆç°è¯ä¹¦À€SSL å¥—æ¥å­—è¯»å–å¤±è´¥À€å®‰å…¨è¿æ¥åˆ‡æ–­À€æœåŠ¡å™¨è¯ä¹¦æ”¹å˜ï¼šæ˜¯å¦è¢«æ‹¦æˆªæ”»å‡»ï¼ŸÀ€æœåŠ¡å™¨è¯ä¹¦æ ¡éªŒå¤±è´¥À€æœåŠ¡å™¨è¯ä¹¦åœ¨ä¸»é¢˜åç§°é—æ¼äº†å±æ€§ commonNameÀ€æœåŠ¡å™¨ä¸èƒ½å‘é€è¯ä¹¦é“¾À€å¥—æ¥å­—æ•°é‡è¶…è¿‡ FD_SETSIZEÀ€æœªçŸ¥é”™è¯¯À€å“åº”ä¸­çš„ä¼ è¾“ä»£ç æœªçŸ¥À€åœ¨ %d è¡Œè§£æ XML é”™è¯¯: %sÀ€åœ¨ %d è¡Œè§£æ XML é”™è¯¯ï¼šéæ³•å…ƒç´ åç§°À€[éæ³•æ—¥æœŸ]À€[éæ‰“å°å­—ç¬¦:#%lu]À€[éæ‰“å°å­—ç¬¦]À€è¯ä¹¦å·²ç»è¿‡æ—¶À€è¯ä¹¦è¿˜æœªç”Ÿæ•ˆÀ€æ­¤è¯ä¹¦æ˜¯ä¸ºä¸åŒçš„ä¸»æœºåç§°é¢å‘À€ä¸èƒ½è§£ææŒ‘æˆ˜À€åœ¨æ‘˜è¦æŒ‘æˆ˜ä¸­çš„ä¸èƒ½è§£æåŸŸÀ€è¢«å¿½ç•¥çš„ %s æŒ‘æˆ˜À€å¿½ç•¥åç»­çš„ç©ºç£‹å•†À€åœ¨æ‘˜è¦æŒ‘æˆ˜ä¸­çš„ç®—æ³•ä¸å…¼å®¹À€é™ˆæ—§çš„åˆå§‹åŒ–æ‘˜è¦æŒ‘æˆ˜À€éæ³•ç£‹å•†ä»¤ç‰ŒÀ€è¯ä¹¦å‘è¡Œè€…ä¸è¢«ä¿¡ä»»À€åœ¨æ‘˜è¦æŒ‘æˆ˜ä¸­çš„å‚æ•°ä¸¢å¤±À€åœ¨åŸºæœ¬æŒ‘æˆ˜ä¸­ä¸¢å¤±äº†é¢†åŸŸÀ€éæ³•åç§»À€è¢«æ‹’ç»çš„ %s æŒ‘æˆ˜À€é™ˆæ—§çš„æ‘˜è¦æŒ‘æˆ˜ç”¨äºæ–°ç®—æ³•æˆ–æ–°é¢†åŸŸÀ€åœ¨æ‘˜è¦æŒ‘æˆ˜ä¸­çš„ç®—æ³•ä¸å¯è¯†åˆ«À€