<?php
// Automatically Generated by TestLink Installer - Mon, 24 Jun 13 15:00:46 +0800
define('DB_TYPE', 'mysql');
define('DB_USER', 'root');
define('DB_PASS', 'kortide');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
